"""initial transaction lab schema

Revision ID: 7d1eba9f42b3
Revises:
Create Date: 2026-09-30 16:38:08.832565
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7d1eba9f42b3"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_records",
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column("namespace", sa.String(length=128), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("protocol", sa.String(length=64), nullable=False),
        sa.Column("protocol_version", sa.String(length=32), nullable=False),
        sa.Column("retrieval_method", sa.String(length=64), nullable=False),
        sa.Column("adapter_version", sa.String(length=32), nullable=False),
        sa.Column("transformation_version", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("conflict_status", sa.String(length=32), nullable=False),
        sa.Column("evidence_level", sa.String(length=16), nullable=False),
        sa.Column("raw_reference", sa.String(length=128), nullable=False),
        sa.Column("normalized_payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("evidence_id"),
    )
    op.create_index(
        "ix_evidence_tenant_transaction",
        "evidence_records",
        ["tenant_id", "transaction_id", "received_at"],
        unique=False,
    )
    op.create_table(
        "ledger_entries",
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("account", sa.String(length=64), nullable=False),
        sa.Column("entry_type", sa.String(length=40), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("reference", sa.String(length=128), nullable=False),
        sa.Column("simulation_only", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    op.create_index(
        "ix_ledger_tenant_transaction",
        "ledger_entries",
        ["tenant_id", "transaction_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "reconciliation_records",
        sa.Column("reconciliation_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("expected_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("observed_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("difference_minor", sa.BigInteger(), nullable=True),
        sa.Column("reason_codes", sa.JSON(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("owner", sa.String(length=128), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("reconciliation_id"),
        sa.UniqueConstraint(
            "tenant_id", "transaction_id", name="uq_reconciliation_tenant_transaction"
        ),
    )
    op.create_index(
        "ix_reconciliation_tenant_status",
        "reconciliation_records",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_table(
        "transaction_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("aggregate_id", sa.String(length=36), nullable=False),
        sa.Column("aggregate_type", sa.String(length=40), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("producer", sa.String(length=64), nullable=False),
        sa.Column("provider_id", sa.String(length=64), nullable=True),
        sa.Column("external_event_id", sa.String(length=128), nullable=True),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("causation_id", sa.String(length=36), nullable=True),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("aggregate_id", "event_version", name="uq_event_aggregate_version"),
        sa.UniqueConstraint(
            "tenant_id", "provider_id", "external_event_id", name="uq_provider_external_event"
        ),
    )
    op.create_index(
        "ix_events_tenant_aggregate",
        "transaction_events",
        ["tenant_id", "aggregate_id", "event_version"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("provider_id", sa.String(length=64), nullable=False),
        sa.Column("scenario", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("reconciliation_status", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("expected_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("billed_amount_minor", sa.BigInteger(), nullable=True),
        sa.Column("refunded_amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("correlation_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_index(
        "ix_transactions_tenant_created", "transactions", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_transactions_tenant_status", "transactions", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("transaction_id", sa.String(length=36), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.transaction_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "key", name="uq_idempotency_tenant_key"),
    )
    if op.get_bind().dialect.name == "postgresql":
        tenant_tables = (
            "transactions",
            "idempotency_records",
            "transaction_events",
            "evidence_records",
            "ledger_entries",
            "reconciliation_records",
        )
        for table in tenant_tables:
            op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
            op.execute(
                f"CREATE POLICY tenant_isolation ON {table} "
                "USING (tenant_id = current_setting('app.tenant_id', true)) "
                "WITH CHECK (tenant_id = current_setting('app.tenant_id', true))"
            )
        op.execute("""
            CREATE FUNCTION enigma_reject_immutable_mutation() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION 'append-only table mutation rejected';
            END;
            $$
        """)
        for table in ("transaction_events", "evidence_records", "ledger_entries"):
            op.execute(
                f"CREATE TRIGGER immutable_{table} BEFORE UPDATE OR DELETE ON {table} "
                "FOR EACH ROW EXECUTE FUNCTION enigma_reject_immutable_mutation()"
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        for table in ("transaction_events", "evidence_records", "ledger_entries"):
            op.execute(f"DROP TRIGGER IF EXISTS immutable_{table} ON {table}")
        op.execute("DROP FUNCTION IF EXISTS enigma_reject_immutable_mutation()")
        for table in (
            "transactions",
            "idempotency_records",
            "transaction_events",
            "evidence_records",
            "ledger_entries",
            "reconciliation_records",
        ):
            op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
            op.execute(f"ALTER TABLE {table} NO FORCE ROW LEVEL SECURITY")
            op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    op.drop_table("idempotency_records")
    op.drop_index("ix_transactions_tenant_status", table_name="transactions")
    op.drop_index("ix_transactions_tenant_created", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("ix_events_tenant_aggregate", table_name="transaction_events")
    op.drop_table("transaction_events")
    op.drop_index("ix_reconciliation_tenant_status", table_name="reconciliation_records")
    op.drop_table("reconciliation_records")
    op.drop_index("ix_ledger_tenant_transaction", table_name="ledger_entries")
    op.drop_table("ledger_entries")
    op.drop_index("ix_evidence_tenant_transaction", table_name="evidence_records")
    op.drop_table("evidence_records")
    # ### end Alembic commands ###
